version: "3.7"
volumes:
    prometheus_data: {}
    grafana_data: {}    
services:
  freqtrade1:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade1
    restart: on-failure
    ports:
      - 14081:8080
    volumes:
      - ./user_data:/freqtrade/user_data
      - ${FT_SECRETS}:/freqtrade/user_data/secrets
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_1.log
      --db-url sqlite:////freqtrade/user_data/dev_1.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_1.json
      --config /freqtrade/user_data/secrets/default-api_server.json
      --strategy Combined_NFIv6_SMA
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/secrets/default-api_server-self.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  freqtrade2:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade2
    restart: on-failure
    ports:
      - 14082:8080
    volumes:
      - ./user_data:/freqtrade/user_data
      - ${FT_SECRETS}:/freqtrade/user_data/secrets
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_2.log
      --db-url sqlite:////freqtrade/user_data/dev_2.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_2.json
      --config /freqtrade/user_data/secrets/default-api_server.json
      --strategy BigZ04
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/secrets/default-api_server-self.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  freqtrade3:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade3
    restart: on-failure
    ports:
      - 14083:8080
    volumes:
      - ./user_data:/freqtrade/user_data
      - ${FT_SECRETS}:/freqtrade/user_data/secrets
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_3.log
      --db-url sqlite:////freqtrade/user_data/dev_3.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_3.json
      --config /freqtrade/user_data/secrets/default-api_server.json
      --strategy CombinedBinHClucAndMADV9
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/secrets/default-api_server-self.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  ftmetric1:
    image: ghcr.io/kamontat/ftmetric:v4.5.1
    container_name: ftmetric1
    restart: on-failure
    ports:
      - 14091:14091
    environment:
      - FTH_FREQTRADE__URL=${FTH_FREQTRADE_HOST}:14082/
      - FTH_FREQTRADE__USERNAME=${FTH_FREQTRADE__USERNAME}
      - FTH_FREQTRADE__PASSWORD=${FTH_FREQTRADE__PASSWORD}
      - FTH_SERVER__PORT=14091
      - FTH_FREQTRADE__CLUSTER=1A
    command: --no-env-file
    depends_on:
      - freqtrade1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${FTH_CLUSTER_HOST_URL}:14091/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  ftmetric2:
    image: ghcr.io/kamontat/ftmetric:v4.3.0
    container_name: ftmetric2
    restart: on-failure
    ports:
      - 14092:14092    
    environment:
      - FTH_FREQTRADE__URL=http://192.168.178.100:14082/
      - FTH_FREQTRADE__USERNAME=${FTH_FREQTRADE__USERNAME}
      - FTH_FREQTRADE__PASSWORD=${FTH_FREQTRADE__PASSWORD}
      - FTH_SERVER__PORT=14092
      - FTH_FREQTRADE__CLUSTER=2A
    command: --no-env-file
    depends_on:
      - freqtrade2
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${FTH_CLUSTER_HOST_URL}:14092/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  ftmetric3:
    image: ghcr.io/kamontat/ftmetric:v4.3.0
    container_name: ftmetric3
    restart: on-failure
    ports:
      - 14093:14093    
    environment:
      - FTH_FREQTRADE__URL=http://192.168.178.100:14083
      - FTH_FREQTRADE__USERNAME=${FTH_FREQTRADE__USERNAME}
      - FTH_FREQTRADE__PASSWORD=${FTH_FREQTRADE__PASSWORD}
      - FTH_SERVER__PORT=14093
      - FTH_FREQTRADE__CLUSTER=3A
    command: --no-env-file
    depends_on:
      - freqtrade3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${FTH_CLUSTER_HOST_URL}:14093/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  prometheus:
    image: prom/prometheus:latest
    restart: on-failure
    container_name: prometheus
    # be aware before open the port
    ports:
       - 14090:9090
    volumes:
      # you can config prometheus via this directory (prometheus.yml)
       - ./prometheus/config:/etc/prometheus/
       - prometheus_data:/prometheus
    depends_on:
      - ftmetric1
      - ftmetric2
      - ftmetric3            
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${FTH_CLUSTER_HOST_URL}:14090/-/healthy"]
      interval: 1m
      timeout: 1s
      retries: 3
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: on-failure
    ports:
      - 14000:14000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:  
      - prometheus
    environment:
      - GF_SERVER_ROOT_URL=${FTH_CLUSTER_HOST_URL}
      - GF_SERVER_HTTP_PORT=14000
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_SECURITY_ADMIN_USER=${FTH_FREQTRADE__USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${FTH_FREQTRADE__PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "${FTH_CLUSTER_HOST_URL}:14000/api/health"]
      interval: 15s
      timeout: 1s
      retries: 3
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: monitoring_node_exporter
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:latest
    command: ["-docker_only"]
    container_name: monitoring_cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8080/cadvisor/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 0
