global:
  scrape_interval: 1m
  scrape_timeout: 5s
scrape_configs:
  - job_name: freqtrade1
    static_configs:
      - targets:
        - "ftmetric1:14091"
  - job_name: freqtrade2
    static_configs:
      - targets:
        - "ftmetric2:14092"
  - job_name: freqtrade3
    static_configs:
      - targets:
        - "ftmetric3:14093"
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100']
